# Change these first
owner: kush992 # Your GitHub organization or username, where this repository lives
repo: up-time-kushbhalodi # The name of this repository

sites:
  - name: KushBhalodi
    url: https://kushbhalodi.com
  - name: Recipes KushBhalodi
    url: https://recipe.kushbhalodi.com
  - name: Grids KushBhalodi
    url: https://grids.kushbhalodi.com
  - name: Pierogi Villa
    url: https://pierogi-villa.kushbhalodi.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.kushbhalodi.com
  # baseUrl: /your-repo-name
  logoUrl: https://img.kushbhalodi.com/images/kushbhalodi.png
  name: <KushBhalodi />
  # introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  # introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
